name: Check
on: pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: .github/actions/yarn
      - run: |
          yarn run build
      - run: |
          yarn run lint
