name: Contracts
on:
  push:
    branches:
      - alpha
      - beta
      - main
  pull_request:
jobs:
  contracts:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
      - run: |
          yarn install --frozen-lockfile
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - run: |
          yarn run build
      - run: |
          forge test -vvv --gas-report
