name: Contracts
on:
  push:
    branches:
      - alpha
      - beta
      - main
  pull_request:
jobs:
  contracts:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
      - run: |
          yarn install --frozen-lockfile
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - if: github.event_name == 'push'
        run: |
          forge test -vvv --gas-report
      - if: github.event_name == 'pull_request'
        id: changed-files
        uses: tj-actions/changed-files@main
        with:
          files: |
            **/*.t.sol
      - if: github.event_name == 'pull_request'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            forge test -vvv --gas-report -c $file
          done
      - if: contains(steps.changed-files.outputs.deleted_files, '.gitmodules')
        run: |
          forge test --vvv
