name: Contracts
on:
  push:
    branches:
      - alpha
      - beta
      - main
  pull_request:
jobs:
  contracts:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yarn
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - if: github.event_name == 'push'
        run: |
          forge test -vvv --ffi --gas-report
      - if: github.event_name == 'pull_request'
        id: changed-files
        uses: tj-actions/changed-files@main
        with:
          files: |
            lib/**
            **/*.sol
      - if: github.event_name == 'pull_request'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            forge test -vvv --ffi --gas-report -c $file
          done
