name: Docker
on:
  workflow_dispatch:
  workflow_call:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: "shunkakinoki"
          password: ${{ secrets.ACCESS_TOKEN }}
          repository: shunkakinoki/contracts
          tags: latest
