name: Release
on:
  push:
    branches:
      - alpha
      - beta
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yarn
      - run: |
          yarn run build
      - run: |
          yarn run release
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
