name: Scripts
on:
  workflow_dispatch:
    inputs:
      contract:
        required: true
        type: string
      rpc:
        required: true
        type: string
      sig:
        required: false
        default: "run()"
        type: string
jobs:
  scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - run: |
          RPC_URL=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.rpc' )
          echo "::add-mask::$RPC_URL"
          forge script ${{ github.event.inputs.contract }} -vvvvv --rpc-url $RPC_URL --broadcast --private-key $WALLET_PRIVATE_KEY --sig '${{ github.event.inputs.sig }}'
        env:
          WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
      - uses: actions/setup-node@v2
      - run: |
          yarn install --frozen-lockfile
      - run: |
          yarn run build
      - run: |
          yarn run fix
      - uses: stefanzweifel/git-auto-commit-action@v4
