name: Scripts
on:
  workflow_dispatch:
    inputs:
      contract:
        required: true
        type: string
      rpc:
        required: true
        type: string
      sig:
        required: true
        default: "run()"
        type: string
jobs:
  scripts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yarn
      - run: |
          yarn run build
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - run: |
          RPC_URL=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.rpc' )
          echo "::add-mask::$RPC_URL"
          forge script ${{ github.event.inputs.contract }} -vvvvv --rpc-url $RPC_URL --broadcast --private-key $WALLET_PRIVATE_KEY --sig '${{ github.event.inputs.sig }}' --verify --etherscan-api-key $ETHERSCAN_API_KEY
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
      - if: always()
        run: |
          yarn run fix
      - if: always()
        uses: stefanzweifel/git-auto-commit-action@v4
